# Site settings
title: DanziFire
email: danzifire@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  DanziFire's Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://danzifire.github.io" # the base hostname & protocol for your site
#twitter_username: username
github_username: danzifire

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
